AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create S3 bucket with versioning enabled'
Parameters:
  BucketName:
    Type: String


Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket